import Head from 'next/head';
import { useNetwork } from 'wagmi'
import { NETWORK_ID } from '../config';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { GetGreeter, SetGreeter, ViewProjects } from '../components/contract';

export default function Home() {
  const { chain, chains } = useNetwork()
  if(chain && chain.id != Number(NETWORK_ID)){
    return(
      <>
        <h1>Wrong ChainID </h1>
        <h3>Please Shift to Chain: {Number(NETWORK_ID)}</h3>
      </>
      
    )
  }
  return (
    <div className={''}>
      <Head>
        <title>Create-Web3 App</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <header style={{ padding: '1rem' }}>
        <ConnectButton />
      </header> */}

      <main
        style={{
          minHeight: '60vh',
          flex: '1',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <GetGreeter />
        <SetGreeter />
        <ViewProjects />
      </main>
    </div>
  );
}
